# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iter_logmap_c <- function(r, maxit = 100L) {
    .Call('_chaos_iter_logmap_c', PACKAGE = 'chaos', r, maxit)
}

iter_mandelbrot_c <- function(c, maxit = 100L, tol = 1e-6) {
    .Call('_chaos_iter_mandelbrot_c', PACKAGE = 'chaos', c, maxit, tol)
}

